### ISSUE TITLE
Please add version key to manifest file so this will keep working with Home Assistant 

### ISSUE THREAD

**Issue by awshirley** [gregoryduckworth/GoogleGeocode-HASS#10]
**Describe the bug**
Missing version key

**To Reproduce**
No 'version' key in the manifest file for custom integration 'google_geocode'. As of Home Assistant 2021.6, this integration will no longer be loaded. Please report this to the maintainer of 'google_geocode'
No 'version' key in the manifest file for custom integration 'satellitetracker'. As of Home Assistant 2021.6, this integration will no longer be loaded. Please report this to the maintainer of 'satellitetracker'

**Expected behavior**
Not to see an error message in my logs regarding this issue.

**Screenshots**

**Home Assistant Version (please complete the following information):**
 - OS: Docker
 - Version 2021.4.0

**Comment by gregoryduckworth** [comment]
Thanks for the heads up!

This should be resolved with #11
