### ISSUE TITLE
Unable to install via HACS

### ISSUE THREAD

**Issue by Turbo-noises** [gregoryduckworth/GoogleGeocode-HASS#13]
Hi there, I am attempting to install this add-on via HACS, I have installed the repo from HACS but the integration doesn't actually appear in the list of integrations to add when I search Google, I've tried updating everything, reinstalling, clearing cache, no dice
Thanks 

Running Home assistant supervised on Ubuntu 20.04 server

**Comment by gregoryduckworth** [comment]
What was the fix? Did you try to configure it through the YAML?

**Comment by Turbo-noises** [comment]
The solution was RTFM (read the fuckin manual) haha, every other
integration I had installed required you to go to
configuration>integrations and add it there after the fact, also I had a
slight misunderstanding of the function of the integration, I was
attempting to use the location data I was already sharing with Google maps
(natively via Android phone) to track my location in an attempt to save
battery, I since realised that the Integration didn't work like that and I
caved and used the companion app for tracking location instead, as soon as
I did that your integration worked flawlessly and does indeed show my
address, entirely my bad sorry for any confusion!
