### ISSUE TITLE
Need to implement device_state_attributes

### ISSUE THREAD

**Issue by awshirley** [gregoryduckworth/GoogleGeocode-HASS#16]
Source: helpers/entity.py:549
First occurred: January 3, 2022, 11:40:27 PM (1 occurrences)
Last logged: January 3, 2022, 11:40:27 PM

Entity sensor.xxx_ariela_current_location (<class 'custom_components.google_geocode.sensor.GoogleGeocode'>) implements device_state_attributes. Please report it to the custom component author.

**Comment by gregoryduckworth** [comment]
Should be resolved in https://github.com/gregoryduckworth/GoogleGeocode-HASS/releases/tag/0.1.8

**Comment by gregoryduckworth** [comment]
Closing now as no further issues.
