### ISSUE TITLE
is it available to show another language?

### ISSUE THREAD

**Issue by geochilmaru** [gregoryduckworth/GoogleGeocode-HASS#3]
Hi,

I would like to use this to my ha. Unfortunately I do live in US. So is it possible way to change another language? Such as Korean.

**Comment by gregoryduckworth** [comment]
Happy to accept PRs on this (or if I get time to do it), you would need to do something similar to:

```
if self._api_key == 'no key':
  url = "https://maps.google.com/maps/api/geocode/json?language=" + self._language + "&latlng=" + lat
else:
  url = "https://maps.googleapis.com/maps/api/geocode/json?language=" + self._language + "&latlng=" + lat + "&key=" + self._api_key
```

**Comment by geochilmaru** [comment]
It works well. Great!!! Thanks a lot!
