### ISSUE TITLE
Integration stopped working after upgrade to Home Assistant 0.112.1

### ISSUE THREAD

**Issue by jsBlackBelt** [gregoryduckworth/GoogleGeocode-HASS#9]
**Describe the bug**
The integration worked flawlessly until the upgrade to Home Assistant 0.112.1

**To Reproduce**
1. upgrade to Home Assistant 0.112.1
2. wait for poll interval to elapse
3. location is not reported, Google Maps API dashboard shows no API requests

**Expected behavior**
Integration should work as before the upgrade

**Home Assistant Version (please complete the following information):**
 - OS: Docker
 - Version Home Assistant 0.112.1

**Comment by gregoryduckworth** [comment]
I’ll look into it, are you able to provide any logs?

**Comment by jsBlackBelt** [comment]
Sure. Where can I find them?

**Comment by gregoryduckworth** [comment]
In the logger component you should be able to set the component to log (https://www.home-assistant.io/integrations/logger/) and then on the configuration page in home assistant there is a log section.

I’m on mobile so can’t remember the exact place it has been moved to.

**Comment by jsBlackBelt** [comment]
OK, U'll try to configure that later today.
However - reinstalling the integration via HACS solved it, and location is back to working and reporting geocoded data, so there is a workaround

**Comment by gregoryduckworth** [comment]
Closing this as there is a valid workaround.
